In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
while True:
    print('1. press 1 to load csv')
    print('2. adding the column')
    print('3. Deleting the column')
    print('4. Inserting the row')
    print('5. Deleting the row')
    print('6. Renaming the column')
    print('7. Displaying the column')
    print('8. Displaying a row')
    print('9. Plotting the line chart')
    ch=int(input("Enter Your Choice-:"))
    if ch==1:
           m1=pd.read_csv("C:/Users/vaima/OneDrive/Desktop/IPL 2024 IP HHW.csv")
           d1=pd.DataFrame(m1)
           print(d1)
    elif ch==2:
        s=input("enter column name")
        l=[]
        for i in range(0,25):
            a=int(input("enter value "))
            l.append(a)
        d1[s]=l
        print(d1)
    elif ch==3:
           x=input("enter column you wish to delete")
           d1=d1.drop(x,axis=1)
           print(d1)
    elif ch==4:
           m1=pd.read_csv("C:/Users/vaima/OneDrive/Desktop/IPL 2024 IP HHW.csv")
           d1=pd.DataFrame(m1)
           d1.loc[25]=[26,'DINESH KARTIK',11,9,4,283,83,56,60]
           print(d1)
    elif ch==5:
           m1=pd.read_csv("C:/Users/vaima/OneDrive/Desktop/IPL 2024 IP HHW.csv")
           d1=pd.DataFrame(m1)
           d1=d1.drop(25,axis=0)
           print(d1)
    elif ch==6:
           m1=pd.read_csv("C:/Users/vaima/OneDrive/Desktop/IPL 2024 IP HHW.csv")
           d1=pd.DataFrame(m1)
           d1=d1.rename({'NAME':'NAME OF PLAYER'},axis='columns')
           print(d1)
    elif ch==7:
           m1=pd.read_csv("C:/Users/vaima/OneDrive/Desktop/IPL 2024 IP HHW.csv")
           d1=pd.DataFrame(m1)
           print(d1.loc[:,'NAME'])
    elif ch==8:
           m1=pd.read_csv("C:/Users/vaima/OneDrive/Desktop/IPL 2024 IP HHW.csv")
           d1=pd.DataFrame(m1)
           print(d1.loc[0:1])
    elif ch==9:
           m1=pd.read_csv("C:/Users/vaima/OneDrive/Desktop/IPL 2024 IP HHW.csv")
           d1=pd.DataFrame(m1)
           plt.plot(d1.rearcamerapixels,d1.nameofmobile)
           plt.xlabel('runs scored')
           plt.ylabel('name of player')
           plt.title('run scored v/s name of player')
           plt.show() 
    else:
           print('Your Choice not found')

1. press 1 to load csv
2. adding the column
3. Deleting the column
4. Inserting the row
5. Deleting the row
6. Renaming the column
7. Displaying the column
8. Displaying a row
9. Plotting the line chart

Enter Your Choice-: 1

    S.NO        NAMEOFPLAYER  MATCHES  INNINGS  NOT OUT  RUNSSCORED  HIGHEST  \
0      1         VIRAT KOLHI       11       11        3         542      113
1      2     RITURAJ GAIKWAD       11       11        2         541      108
2      3        SANJU SAMSON       11       11        4         471       86
3      4        SUNIL NARINE       11       11        0         461      109
4      5         TRAVIS HEAD       10       10        0         444      102
5      6         RIYAN PARAG       11       10        2         436       84
6      7            KL RAUHL       11       11        0         431       82
7      8           PHIL SALT       11       11        1         429       89
8      9       SAI SUDHARSAN       11       11        1         424       84
9     10        RISHABH PANT       12       12        2         413       88
10    11         TILAK VERMA       12       12        3         384       65
11    12      FAF DU PLESSIS       11       11        0         352       64
12    13      MARCUS STOINIS       11       11        2         352      124
13    14         SHIVAM DUBE       11       11        3         350       66
14    15    HEINRICH KHAASEN       11       11        3         339       80
15    16         JOS BUTTLER       10       10        2         338      107
16    17    SURYAKUMAR YADAV        9        9        1         334      102
17    18        ROHIT SHARMA       12       12        1         330      105
18    19     ABHISHEK SHARMA       11       11        0         326       63
19    20        SHUBMAN GILL       11       11        1         322       89
20    21    YASHASVI JAISWAL       11       11        1         320      104
21    22      TRISTAN STUBBS       12       11        5         318       71
22    23      SHASHANK SINGH       11       11        6         315       68
23    24     NICHOLAS POORAN       11       11        5         315       64
24    25  JAKE FRASER-MCGURK        7        7        0         309       84

    AVERAGE
0     67.75
1     60.11
2     67.29
3     41.91
4     44.40
5     54.50
6     39.18
7     42.90
8     42.40
9     41.30
10    42.67
11    32.00
12    39.11
13    43.75
14    42.38
15    42.25
16    41.75
17    30.00
18    29.64
19    32.20
20    32.00
21    53.00
22    63.00
23    52.50
24    44.14
1. press 1 to load csv
2. adding the column
3. Deleting the column
4. Inserting the row
5. Deleting the row
6. Renaming the column
7. Displaying the column
8. Displaying a row
9. Plotting the line chart

Enter Your Choice-: 2
enter column name hundred
enter value  1
enter value  1
enter value  1
enter value  1
enter value  0
enter value  0
enter value  0
enter value  0
enter value  0
enter value  0
enter value  0
enter value  0
enter value  0
enter value  0
enter value  0
enter value  0
enter value  0
enter value  0
enter value  0
enter value  0
enter value  0
enter value  0
enter value  0
enter value  0
enter value  0

    S.NO        NAMEOFPLAYER  MATCHES  INNINGS  NOT OUT  RUNSSCORED  HIGHEST  \
0      1         VIRAT KOLHI       11       11        3         542      113
1      2     RITURAJ GAIKWAD       11       11        2         541      108
2      3        SANJU SAMSON       11       11        4         471       86
3      4        SUNIL NARINE       11       11        0         461      109
4      5         TRAVIS HEAD       10       10        0         444      102
5      6         RIYAN PARAG       11       10        2         436       84
6      7            KL RAUHL       11       11        0         431       82
7      8           PHIL SALT       11       11        1         429       89
8      9       SAI SUDHARSAN       11       11        1         424       84
9     10        RISHABH PANT       12       12        2         413       88
10    11         TILAK VERMA       12       12        3         384       65
11    12      FAF DU PLESSIS       11       11        0         352       64
12    13      MARCUS STOINIS       11       11        2         352      124
13    14         SHIVAM DUBE       11       11        3         350       66
14    15    HEINRICH KHAASEN       11       11        3         339       80
15    16         JOS BUTTLER       10       10        2         338      107
16    17    SURYAKUMAR YADAV        9        9        1         334      102
17    18        ROHIT SHARMA       12       12        1         330      105
18    19     ABHISHEK SHARMA       11       11        0         326       63
19    20        SHUBMAN GILL       11       11        1         322       89
20    21    YASHASVI JAISWAL       11       11        1         320      104
21    22      TRISTAN STUBBS       12       11        5         318       71
22    23      SHASHANK SINGH       11       11        6         315       68
23    24     NICHOLAS POORAN       11       11        5         315       64
24    25  JAKE FRASER-MCGURK        7        7        0         309       84

    AVERAGE  hundred
0     67.75        1
1     60.11        1
2     67.29        1
3     41.91        1
4     44.40        0
5     54.50        0
6     39.18        0
7     42.90        0
8     42.40        0
9     41.30        0
10    42.67        0
11    32.00        0
12    39.11        0
13    43.75        0
14    42.38        0
15    42.25        0
16    41.75        0
17    30.00        0
18    29.64        0
19    32.20        0
20    32.00        0
21    53.00        0
22    63.00        0
23    52.50        0
24    44.14        0
1. press 1 to load csv
2. adding the column
3. Deleting the column
4. Inserting the row
5. Deleting the row
6. Renaming the column
7. Displaying the column
8. Displaying a row
9. Plotting the line chart

Enter Your Choice-: 3
enter column you wish to delete HIGHEST

    S.NO        NAMEOFPLAYER  MATCHES  INNINGS  NOT OUT  RUNSSCORED  AVERAGE  \
0      1         VIRAT KOLHI       11       11        3         542    67.75
1      2     RITURAJ GAIKWAD       11       11        2         541    60.11
2      3        SANJU SAMSON       11       11        4         471    67.29
3      4        SUNIL NARINE       11       11        0         461    41.91
4      5         TRAVIS HEAD       10       10        0         444    44.40
5      6         RIYAN PARAG       11       10        2         436    54.50
6      7            KL RAUHL       11       11        0         431    39.18
7      8           PHIL SALT       11       11        1         429    42.90
8      9       SAI SUDHARSAN       11       11        1         424    42.40
9     10        RISHABH PANT       12       12        2         413    41.30
10    11         TILAK VERMA       12       12        3         384    42.67
11    12      FAF DU PLESSIS       11       11        0         352    32.00
12    13      MARCUS STOINIS       11       11        2         352    39.11
13    14         SHIVAM DUBE       11       11        3         350    43.75
14    15    HEINRICH KHAASEN       11       11        3         339    42.38
15    16         JOS BUTTLER       10       10        2         338    42.25
16    17    SURYAKUMAR YADAV        9        9        1         334    41.75
17    18        ROHIT SHARMA       12       12        1         330    30.00
18    19     ABHISHEK SHARMA       11       11        0         326    29.64
19    20        SHUBMAN GILL       11       11        1         322    32.20
20    21    YASHASVI JAISWAL       11       11        1         320    32.00
21    22      TRISTAN STUBBS       12       11        5         318    53.00
22    23      SHASHANK SINGH       11       11        6         315    63.00
23    24     NICHOLAS POORAN       11       11        5         315    52.50
24    25  JAKE FRASER-MCGURK        7        7        0         309    44.14

    hundred
0         1
1         1
2         1
3         1
4         0
5         0
6         0
7         0
8         0
9         0
10        0
11        0
12        0
13        0
14        0
15        0
16        0
17        0
18        0
19        0
20        0
21        0
22        0
23        0
24        0
1. press 1 to load csv
2. adding the column
3. Deleting the column
4. Inserting the row
5. Deleting the row
6. Renaming the column
7. Displaying the column
8. Displaying a row
9. Plotting the line chart

In [ ]:
m1=pd.read_csv("C:/Users/vaima/OneDrive/Desktop/IPL 2024 IP HHW.csv")
           d1=pd.DataFrame(m1)
           plt.plot(d1.rearcamerapixels,d1.nameofmobile)
           plt.xlabel('runs scored')
           plt.ylabel('name of player')
           plt.title('run scored v/s name of player')
           plt.show()